### PR TITLE
Run script

### PR DESCRIPTION
**Pull request by nottrobin**
QA
--

``` bash
./run clean
./run
./run build
./run watch --watch-site
etc.
```

Check the README.md too.

### CODE REVIEW

**Comment by nottrobin** [comment]
[Add ./run script](https://trello.com/c/dK7NyUZL/3300-add-run-script)

**Comment by barrymcgee** [comment]
From testing this I've found - 

`./run clean` - cleans all build assets.
`./run` - generates site, runs server and watches for .md changes but not .scss before regenerating
`./run build` - builds all assets.
`./run watch` - watches Sass files only
`./run watch --watch-site` - this watches Sass files but doesn't seem to do anything when changing .md files?

**Comment by nottrobin** [comment]
thanks @barrymcgee I'll look into that

**Comment by barrymcgee** [comment]
@nottrobin Also, regenerating the site takes ~45secs 😬

**Comment by nottrobin** [comment]
@barrymcgee can you confirm if it's any slower than it was? I can't think of any reason why it would be.

**Comment by nottrobin** [comment]
@barrymcgee the site builds from scratch in 3.7 seconds for me

**Comment by nottrobin** [comment]
@barrymcgee I think the problem wasn't that it wasn't watching, it was, as you pointed out, that it was building *very slowly*.

I've sped it up a couple of orders of magnitude by ignoring the `node_modules` folder. Try it out now? I hope you'll find that watching the site works well.

Note that not only does `./run watch --watch-site` watch for jekyll changes, but `./run` and `./run serve` should too.

**Comment by barrymcgee** [comment]
Runs much faster and watchers now work 👍

**Pull request merged**
