### PR TITLE
Pictos: Update page copy

### LINKED ISSUE #62: /pictogram page needs to be updated to match live

### PR DESCRIPTION
**Pull request by deadlight**
## Done

Made pictogram copy match the live site

## QA

 - ./run
 - Navigate to [the pictogram page](http://localhost:8011/brand/pictograms/)
 - Compare with [live](http://design.ubuntu.com/brand/pictograms)

## Issue / Card

Fixes #62

### CODE REVIEW

**Comment by barrymcgee** [comment]
The grid is broken on that page, check the "Back to top" links

screen shot 2017-08-24 at 17 55 35

**Comment by deadlight** [comment]
@barrymcgee apologies, the scope of this review is the content, I should have been clearer. The current master has the same odd use of the build.

The placement of the navigation menu will be addressed in the upcoming vanilla upgrade and navigation rebuild.

**Comment by deadlight** [comment]
@barrymcgee oh, wait... I see what you mean. Will fix.

**Comment by deadlight** [comment]
@barrymcgee ready for re-review

**Comment by barrymcgee** [comment]
@deadlight Still seeing grid weirdness where nesting strips and rows means that the content area is not filling the full `col-8` available to it which means it's not lining up with the footer.

screen shot 2017-09-01 at 15 01 24

**Comment by deadlight** [comment]
@barrymcgee I found the problem with nested col-*, I'll create an issue to fix other instances across the site but I've fixed this one for now.

**Pull request merged**
