### PR TITLE
Remove text section

### PR DESCRIPTION
**Pull request by deadlight**
## Done

Removed the `/brand/text` page

## QA

 - `./run`
 - See that /brand/text no longer exists
 - See that there are no references to the page on /brand

### CODE REVIEW

**Comment by barrymcgee** [comment]
There is still a link to this page in `_includes/_side-nav-brand.html`

I removed it myself and tried to push the change to your feature branch but don't seem to have permission.

**Comment by deadlight** [comment]
@barrymcgee this PR allows edits from maintainers. Try forcing.

**Comment by barrymcgee** [comment]
screen shot 2017-07-06 at 11 14 09

😢

**Comment by deadlight** [comment]
@barrymcgee it looks like you might have used the https: rather than the git: protocol to clone the repo. That might be causing your auth problems.

**Comment by deadlight** [comment]
@barrymcgee can you re-review, please? I can see the link being removed in `_includes/_side-nav-brand.html` (I just confirmed looking on the files tab)

**Comment by barrymcgee** [comment]
@deadlight Weird it doesn't even appear in this activity feed, but yes, I now see it in 'Files changed'

**Pull request merged**
